# Generated by Django 4.2.7 on 2023-11-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=250)),
                ("last_name", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                ("job", models.CharField(max_length=250)),
                ("avatar", models.ImageField(blank=True, upload_to="users/%Y/%m/%d")),
            ],
        ),
        migrations.CreateModel(
            name="MusicStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=250)),
                ("last_name", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                ("subject", models.CharField(max_length=250)),
                ("avatar", models.ImageField(blank=True, upload_to="users/%Y/%m/%d")),
            ],
        ),
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=250)),
                ("last_name", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                ("birthdate", models.DateField()),
                ("subject", models.CharField(max_length=250)),
                ("city", models.CharField(max_length=250)),
                ("job", models.CharField(max_length=250)),
                ("hobbies", models.CharField(max_length=250)),
                ("avatar", models.ImageField(blank=True, upload_to="users/%Y/%m/%d")),
                ("musicstyle", models.ManyToManyField(to="participants.musicstyle")),
            ],
        ),
    ]
