# Generated by Django 4.2.7 on 2023-11-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competitor",
            options={"ordering": ["-first_name"]},
        ),
        migrations.AlterModelOptions(
            name="judge",
            options={"ordering": ["-first_name"]},
        ),
        migrations.AlterModelOptions(
            name="musicstyle",
            options={"ordering": ["-name"]},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"ordering": ["-first_name"]},
        ),
        migrations.AddIndex(
            model_name="competitor",
            index=models.Index(
                fields=["-first_name"], name="participant_first_n_ff6b62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judge",
            index=models.Index(
                fields=["-first_name"], name="participant_first_n_d623ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="musicstyle",
            index=models.Index(fields=["-name"], name="participant_name_d8a34a_idx"),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["-first_name"], name="participant_first_n_246d72_idx"
            ),
        ),
    ]
