# Generated by Django 5.0 on 2023-12-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_competitor_options_alter_judge_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicstyle',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='musicstyle',
            name='participant_name_d8a34a_idx',
        ),
        migrations.AlterField(
            model_name='competitor',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AddIndex(
            model_name='musicstyle',
            index=models.Index(fields=['name'], name='participant_name_5dcb9c_idx'),
        ),
    ]
